modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/NRD-inc/HTTYMD-2/issues" #optional
displayURL="http://www.httymd.com/" #optional
#logoFile="examplemod.png" #optional
credits="Thank you, Dreamworks, for bringing this lovely franchise to life." #optional
authors="Gwen, Lacy99, NukeRubberDucky, Tiki, Mnesikos" #optional

[[mods]] #mandatory
modId="httymd" #mandatory
version="${version}" #mandatory
displayName="How To Train Your Minecraft Dragon 2" #mandatory
#updateJSONURL="http://myurl.me/" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A minecraft mod that bring the world of HTTYD to your game.
'''

[[dependencies.httymd]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
